AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - "tasks/**/*"
    - "vendor/**/*"

Style:
  Enabled: false

Layout:
  Enabled: false

Metrics:
  Enabled: false

Bundler:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

# TODO: enable it in a future because `ruby -w` warns it
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# TODO: enable it in a future because `ruby -w` warns it
Lint/AmbiguousOperator:
  Enabled: false
